lvim.builtin.alpha.active = true
lvim.builtin.bufferline.options.always_show_bufferline = true
lvim.builtin.bufferline.options.close_command = "Bdelete! %d"
-- lvim.builtin.terminal.active = true
lvim.builtin.notify.active = true
lvim.builtin.nvimtree.setup.renderer.icons.show.git = false
lvim.builtin.nvimtree.setup.filters.custom = { "\\.git", "\\.cache", "\\.DS_Store" }
lvim.builtin.nvimtree.setup.filters.exclude = { ".gitignore" }
-- lvim.builtin.dap.active = true
